# Generated by Django 4.2.7 on 2024-06-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_transaction_sale_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
