# Generated by Django 4.2.7 on 2024-06-30 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_medicine_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='issue_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
